const splash = (champion) => `https://ddragon.leagueoflegends.com/cdn/img/champion/splash/${champion}_0.jpg`;

export const platformCards = [
  {
    key: 'ven',
    title: 'VEN',
    kicker: 'Fast VEN suite',
    href: 'ven/',
    image: splash('Zed'),
    stats: ['6 champions', 'smart pred', 'fight-ready controls'],
    body: 'A focused lineup for players who want crisp combos, cleaner kill windows, and readable in-game controls.',
  },
  {
    key: 'hanbot',
    title: 'Hanbot',
    kicker: 'Rift+ script suite',
    href: 'hanbot/',
    image: splash('Ezreal'),
    stats: ['30 champions', 'clean setup', 'Telegram + Discord'],
    body: 'A broad champion lineup for players who want quick setup, familiar controls, and picks that are easy to browse.',
  },
];

export const venSuite = {
  key: 'ven',
  name: 'VEN',
  platformLabel: 'DanZAIO // VEN suite',
  headline: 'Sharper fights for the champions you actually play.',
  lede: 'A focused VEN lineup with cleaner combos, smarter skillshots, safer all-ins, and useful on-screen information.',
  heroImage: splash('Zed'),
  panelImage: splash('Jinx'),
  stats: [
    { label: 'Supported champions', value: '6', note: 'Ezreal, Jinx, Pyke, Samira, Shyvana, and Zed are ready to play on VEN.' },
    { label: 'Platform', value: 'VEN', note: 'Made for VEN players who want responsive controls and fast champion setup.' },
    { label: 'Core feel', value: 'Sharp', note: 'Skillshots, kill windows, safety checks, and visuals stay close to the fight.' },
  ],
  signals: ['champions // ready now', 'skillshots // smarter timing', 'fights // safer all-ins', 'support // telegram + discord'],
  supportLinks: [
    { text: 'Champions', href: '#all-champions' },
    { text: 'Request champion', action: 'new-champion' },
    { text: 'Discord', href: 'https://dsc.gg/danzaio' },
  ],
  features: [
    {
      kicker: 'Ready to play',
      title: 'Pick a champion and get straight into the game.',
      body: 'The VEN lineup focuses on six polished picks with clear controls, readable options, and tools that matter in actual fights.',
    },
    {
      kicker: 'Skillshots',
      title: 'Land more of the spells that decide fights.',
      body: 'Key casts are built around smarter timing, better target choice, and options you can tune without slowing down your setup.',
    },
    {
      kicker: 'Combat flow',
      title: 'Champion flow follows the way the pick wants to win.',
      body: 'Ezreal keeps pressure high, Jinx plays for resets, Pyke hunts executes, Samira builds style, Shyvana forces dragon pressure, and Zed looks for lethal shadows.',
    },
    {
      kicker: 'Safer aggression',
      title: 'Go in hard without ignoring danger.',
      body: 'Dash checks, turret awareness, revive and stasis handling, and defensive reactions help aggressive plays feel controlled.',
    },
    {
      kicker: 'In-game clarity',
      title: 'See the information that helps you act faster.',
      body: 'Ranges, damage windows, execute hints, shadow paths, objective cues, and status text stay focused on decisions, not clutter.',
    },
    {
      kicker: 'Feedback',
      title: 'Shape what gets improved next.',
      body: 'Report what feels wrong, ask for a feature, or request a champion from the same page you use to browse the lineup.',
    },
  ],
  champions: [
    {
      name: 'EZREAL',
      label: 'SKILLSHOT',
      role: 'Mystic Shot Control',
      description: 'Keep Mystic Shot pressure high, play around W mark windows, reposition for stronger angles, and finish low-health targets without menu clutter.',
      image: splash('Ezreal'),
      position: 'center top',
      features: ['Smarter Mystic Shot angles and target choice', 'W mark windows that stay easy to follow', 'Arcane Shift support for better Q lines', 'Manual ultimate, kill pressure, farming, and clear visuals'],
    },
    {
      name: 'JINX',
      label: 'HOT',
      role: 'Fishbones Reset Flow',
      description: 'Swap weapons with purpose, punish targets outside auto range, react with Flame Chompers, and play around reset windows with clearer damage information.',
      image: splash('Jinx'),
      position: 'center top',
      features: ['Fishbones and minigun choices that fit the fight', 'Get Excited tracking for reset moments', 'Zap and rocket pressure for long-range kills', 'Chompers reactions, choke control, and damage visuals'],
    },
    {
      name: 'PYKE',
      label: 'EXECUTE',
      role: 'E Magnet Engage',
      description: 'Threaten hooks, chain E stuns, look for clean executes, and avoid wasting Death From Below into saves or bad targets.',
      image: splash('Pyke'),
      position: 'center top',
      features: ['Charged hook pressure with target control', 'E Magnet and E+Flash engage support', 'Execute choices that respect common saves', 'Escape tools and clear execute indicators'],
    },
    {
      name: 'SAMIRA',
      label: 'STYLE',
      role: 'S-Rank All-In',
      description: 'Build style smoothly, protect key all-ins, dash with better awareness, and use Inferno Trigger when the fight is ready for it.',
      image: splash('Samira'),
      position: 'center top',
      features: ['Style flow built around all-in timing', 'Blade Whirl reactions for dangerous moments', 'Dash safety, reset awareness, and chase support', 'Ultimate finishers, kill pressure, and damage visuals'],
    },
    {
      name: 'SHYVANA',
      label: 'DRAGON',
      role: 'Dragon Form Pressure',
      description: 'Manage fury, open fights with better Flame Breath timing, pressure dragon-form engages, and keep objective fights easier to read.',
      image: splash('Shyvana'),
      position: 'center top',
      features: ['Fury and dragon-form awareness', 'Smarter Twin Bite and Burnout timing', 'Flame Breath openers and dragon-form pressure', 'Objective secure help for epic monsters'],
    },
    {
      name: 'ZED',
      label: 'SHADOW',
      role: 'WEQ Kill Windows',
      description: 'Set up shadow angles, land cleaner shuriken pressure, judge Death Mark windows, and keep shadow movement readable during fast fights.',
      image: splash('Zed'),
      position: 'center top',
      features: ['Living Shadow and Death Mark awareness', 'WEQ pressure and lethal target selection', 'Safer all-ins, kill pressure, harass, clear, and last-hit tools', 'Shadow positions, trajectories, Q paths, and damage display'],
    },
  ],
  facts: [
    {
      version: 'Champions',
      date: '6 ready now',
      type: 'VEN lineup',
      title: 'A focused set of champions ready for ranked sessions.',
      bullets: ['Ezreal, Jinx, Pyke, Samira, Shyvana, and Zed are ready to browse.', 'Each champion card shows what the setup helps you do in game.', 'More champions can be requested directly from the page.'],
    },
    {
      version: 'Feel',
      date: 'in game',
      type: 'clean control',
      title: 'The important options stay close and readable.',
      bullets: ['Combo, harass, clear, kill pressure, and visuals stay easy to find.', 'Advanced options are there when you want to tune the champion deeper.', 'Aggressive champions get safety tools so big plays feel more controlled.'],
    },
    {
      version: 'Requests',
      date: 'player feedback',
      type: 'next updates',
      title: 'Tell us what should feel better next.',
      bullets: ['Report a problem from the champion card when something feels wrong.', 'Ask for a feature using normal gameplay examples, clips, or notes.', 'Request the next champion and describe what matters most when playing them.'],
    },
  ],
};

export const hanbotSuite = {
  key: 'hanbot',
  name: 'Rift+ Hanbot',
  locked: true,
  platformLabel: 'Rift+ // Hanbot suite',
  headline: 'Hanbot lineup reveal coming soon.',
  lede: 'The Hanbot page is locked while the lineup is being prepared. Join the community for release updates.',
  heroImage: splash('Ezreal'),
  panelImage: splash('Jinx'),
  stats: [
    { label: 'Status', value: 'TBA', note: 'The Hanbot lineup will be announced when it is ready for players.' },
    { label: 'Platform', value: 'HB', note: 'Rift+ Hanbot details are currently locked.' },
    { label: 'Community', value: 'CHAT', note: 'Telegram and Discord are always one click away.' },
  ],
  signals: ['hanbot // to be announced', 'lineup // locked', 'release // coming soon', 'support // telegram + discord'],
  supportLinks: [
    { text: 'Champions', href: '#all-champions' },
    { text: 'Request champion', action: 'new-champion' },
    { text: 'Discord', href: 'https://dsc.gg/danzaio' },
  ],
  features: [
    { kicker: 'Current lineup', title: '30 supported champions are ready now.', body: 'From Ezreal and Jinx to Pyke, Zed, Senna, Zoe, Mel, Yunara, and more, Rift+ keeps the current lineup easy to scan and easy to pick from.' },
    { kicker: 'Skillshots', title: 'Tune key casts without fighting the menu.', body: 'Supported champions like Ezreal, Jinx, and Blitzcrank give you clear spell controls so important casts feel consistent.' },
    { kicker: 'Core modes', title: 'The essentials stay easy to reach.', body: 'Combo, Harass, Clear, visuals, and kill pressure stay organized so you can shape each champion around your playstyle quickly.' },
    { kicker: 'Useful extras', title: 'The best picks go deeper when they need to.', body: 'Selected champions include manual keys, target rules, defensive reactions, and unique tools that fit how the champion wins fights.' },
    { kicker: 'Champion depth', title: 'Specialist champions keep their identity.', body: 'Ezreal keeps pressure high, Pyke hunts resets, Aphelios plays around weapons, and Zed looks for explosive shadow windows.' },
    { kicker: 'Feedback', title: 'Player requests are one click away.', body: 'Every champion card can open bug reports and feature requests, while the page also accepts new champion requests.' },
  ],
  champions: [
    { name: 'EZREAL', label: 'HOT', role: 'Mystic Shot Pressure', description: 'For players who want reliable poke, W mark windows, and fast access to Ezreal core tools.', image: splash('Ezreal'), position: 'center top' },
    { name: 'ZERI', label: 'UPD', role: 'The Spark of Zaun', description: 'Updated support for players who want a lighter, mobile marksman profile with core options close at hand.', image: splash('Zeri'), position: 'center top' },
    { name: 'JINX', label: 'HOT', role: 'Get Excited Reset', description: 'A high-tempo marksman setup with smarter spell choices, automatic options, clear visuals, and kill pressure tools.', image: splash('Jinx'), position: 'center top' },
    { name: 'JAX', label: 'BETA', role: 'Leap Strike Pressure', description: 'A developing Jax setup for players who want jump-in pressure and simple fighter controls.', image: splash('Jax'), position: 'center top' },
    { name: 'YUNARA', label: 'NEW', role: 'Fresh Champion Support', description: 'Fresh champion support for players who want to try the newest picks as they arrive.', image: 'assets/latest/yunara.jpg', position: 'center center' },
    { name: 'ZAAHEN', label: 'NEW', role: 'The Unsundered', description: 'Early support for players who want to explore a newer champion with Rift+ controls.', image: 'assets/hero/zaahen.jpg', position: 'center top' },
    { name: "KOG'MAW", label: 'RIFT+', role: 'Orbwalker Limit', description: 'A dedicated KogMaw setup built for players who want fast access to core options.', image: splash('KogMaw'), position: 'center top' },
    { name: 'TWITCH', label: 'RIFT+', role: 'Stealth Pressure', description: 'A Twitch setup for players who like ambush windows, poison pressure, and cleaner fight timing.', image: splash('Twitch'), position: 'center top' },
    { name: 'SAMIRA', label: 'HOT', role: 'S-Rank Combo', description: 'For players who want fast all-in flow, reset pressure, and a setup that stays aggressive.', image: splash('Samira'), position: 'center top' },
    { name: 'APHELIOS', label: 'NEW', role: 'Weapon Pair Control', description: 'One of the deepest picks in the lineup, built around weapon flow, fight timing, and safe reset pressure.', image: splash('Aphelios'), position: 'center top' },
    { name: 'CAITLYN', label: 'RIFT+', role: 'Trap Logic', description: 'A Caitlyn setup for players who want cleaner lane pressure, trap control, and fast menu access.', image: splash('Caitlyn'), position: 'center top' },
    { name: "KAI'SA", label: 'RIFT+', role: 'Void Seeker', description: 'A focused KaiSa setup for players who want quick, clean core combat controls.', image: splash('Kaisa'), position: 'center top' },
    { name: 'SHYVANA', label: 'NEW', role: 'Dragon Form Pressure', description: 'For players who want dragon-form engage pressure, Flame Breath value, and clear fight timing.', image: 'assets/hero/shyvana.jpg', position: 'center top' },
    { name: 'QIYANA', label: 'NEW', role: 'Element Combo Control', description: 'For players who want tighter element choices, burst windows, and quick access to key controls.', image: splash('Qiyana'), position: 'center top' },
    { name: 'ZED', label: 'NEW', role: 'Shadow Kill Windows', description: 'For assassin players who want shadow pressure, flash tools, and clearer lethal windows.', image: splash('Zed'), position: 'center top' },
    { name: 'SENNA', label: 'UPD', role: 'Soul Farming', description: 'Updated support for players who want long-range utility, scaling pressure, and a clean Senna setup.', image: splash('Senna'), position: 'center top' },
    { name: 'TRISTANA', label: 'RIFT+', role: 'Explosive Charge', description: 'A Tristana setup made for players who want explosive all-ins without menu clutter.', image: splash('Tristana'), position: 'center top' },
    { name: 'MILIO', label: 'RIFT+', role: 'Campfire Support', description: 'A dedicated Milio setup for players who want support-focused control and clean access to key options.', image: splash('Milio'), position: 'center top' },
    { name: 'BLITZ', label: 'RIFT+', role: 'Hook Pressure', description: 'A hook-first setup with cleaner grabs, utility moments, and quick access to core tools.', image: splash('Blitzcrank'), position: 'center top' },
    { name: 'PYKE', label: 'RIFT+', role: 'Execute Resets', description: 'An engage-heavy setup for hook pressure, E plays, and aggressive execute windows.', image: splash('Pyke'), position: 'center top' },
    { name: 'ORIANNA', label: 'RIFT+', role: 'Ball Management', description: 'A dedicated Orianna setup for players who want ball control and clean access to core pages.', image: splash('Orianna'), position: 'center top' },
    { name: 'XERATH', label: 'RIFT+', role: 'Sniper Mode', description: 'Made for players who want long-range pressure and quick access to their artillery setup.', image: splash('Xerath'), position: 'center top' },
    { name: 'SERAPHINE', label: 'RIFT+', role: 'Double Cast', description: 'A dedicated Seraphine setup for players who want supportive control with clean menu access.', image: splash('Seraphine'), position: 'center top' },
    { name: 'CORKI', label: 'RIFT+', role: 'Package Timer', description: 'A focused Corki setup for players who want package timing support and fast core setup.', image: splash('Corki'), position: 'center top' },
    { name: 'OLAF', label: 'RIFT+', role: 'Axe Pressure', description: 'A direct Olaf setup for players who want aggressive axes without extra clutter.', image: splash('Olaf'), position: 'center top' },
    { name: 'CASSIO', label: 'RIFT+', role: 'Twin Fang', description: 'A dedicated Cassiopeia setup for players who want quick access to core poison-fight control.', image: splash('Cassiopeia'), position: 'center top' },
    { name: 'MEL', label: 'NEW', role: 'Arcane Pressure', description: 'For players who want one of the newer arcane-flavored picks with quick Rift+ access.', image: 'assets/latest/mel.jpg', position: 'center top' },
    { name: 'ZOE', label: 'NEW', role: 'Arcane Skillshots', description: 'A specialist setup for players who want bubble pressure, long-range picks, and fast access to key controls.', image: splash('Zoe'), position: 'center top' },
    { name: 'SYNDRA', label: 'NEW', role: 'Sphere Control', description: 'For players who want tighter sphere pressure, burst windows, and a cleaner mage setup.', image: splash('Syndra'), position: 'center top' },
    { name: 'XAYAH', label: 'NEW', role: 'Feather Control', description: 'For players who want feather-focused fights, cleaner pullback timing, and strong marksman control.', image: splash('Xayah'), position: 'center top' },
  ],
  facts: [
    { version: 'Lineup', date: '30 champions', type: 'ready to browse', title: 'The lineup is broad, fast to scan, and easy to choose from.', bullets: ['Marksmen, assassins, mages, supports, and fighters are all represented.', 'Popular picks are easy to find in one clean champion grid.', 'New champion requests are available when your pick is missing.'] },
    { version: 'Controls', date: 'easy setup', type: 'in game', title: 'The important options stay easy to find.', bullets: ['Combo, Harass, Clear, visuals, and kill pressure are organized around common player needs.', 'Selected champions add manual keys, defensive reactions, and target rules for deeper tuning.', 'Champion-specific tools stay focused on what helps you play the pick better.'] },
    { version: 'Support', date: 'Telegram + Discord', type: 'quick access', title: 'Community access stays close to the action.', bullets: ['Telegram is linked directly from the page.', 'Discord is linked directly from the page.', 'English and Chinese UI text are available where supported.'] },
  ],
};
