export const heroStats = [
  {
    label: 'Supported scripts',
    value: '30',
    note: '30 champion entries are currently listed in the Rift+ lineup.',
  },
  {
    label: 'Name',
    value: 'Rift+',
    note: 'One suite, one lineup, one brand.',
  },
  {
    label: 'Community',
    value: 'TG + DC',
    note: 'Telegram and Discord are linked directly from the suite.',
  },
];

export const suiteSignals = [
  'lineup // 30 supported',
  'menus // champion specific',
  'prediction // supported picks',
  'support // telegram + discord',
];

export const featureCards = [
  {
    kicker: 'Current lineup',
    title: '30 supported champions are ready now.',
    body: 'From Ezreal and Jinx to Pyke, Zed, Senna, Zoe, Mel, Yunara, and more, Rift+ keeps the current lineup easy to scan and easy to pick from.',
  },
  {
    kicker: 'Prediction menus',
    title: 'Dial in prediction the way you like it.',
    body: 'Supported champions like Ezreal, Jinx, and Blitzcrank expose dedicated prediction controls, including hitchance tuning where those pages are available.',
  },
  {
    kicker: 'Core modes',
    title: 'Your core controls stay right where you expect them.',
    body: 'Combo, Harass, and Clear appear across the lineup, so shaping each script around your playstyle stays quick and familiar.',
  },
  {
    kicker: 'Useful extras',
    title: 'More than the basics.',
    body: 'Many entries also ship with Drawings and Killsteal pages, while selected scripts go further with reactive logic, semi-manual keys, and per-enemy controls.',
  },
  {
    kicker: 'Champion depth',
    title: 'The deeper picks stay deep.',
    body: 'Ezreal brings smart targeting and Auto Q tools, Pyke adds E Magnet and E+Flash, Aphelios gets weapon-pair logic, and Zed includes Flash Tech plus reactive settings.',
  },
  {
    kicker: 'Support access',
    title: 'Updates and help stay close.',
    body: 'Telegram and Discord are linked directly in the suite, and the UI supports both English and Chinese text paths.',
  },
];

export const spotlightScripts = [
  {
    name: 'EZREAL',
    title: 'Mystic Shot Prediction',
    laneLabel: 'Menu',
    lane: 'Prediction + Q',
    systemLabel: 'Focus',
    system: 'Smart targeting',
    blurb:
      'Prediction Settings, smart targeting, Auto Q controls, and dedicated Mystic Shot and Essence Flux pages keep Ezreal flexible without feeling bloated.',
    image: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ezreal_0.jpg',
    crest: './assets/crests/piltover.png',
    crestAlt: 'piltover crest',
    href: '#all-champions',
  },
  {
    name: 'PYKE',
    title: 'Execute Resets',
    laneLabel: 'Menu',
    lane: 'Q / E / R',
    systemLabel: 'Focus',
    system: 'E Magnet + safety',
    blurb:
      'Bone Skewer, Phantom Undertow, E Magnet, safety checks, and E+Flash follow tools give Pyke players more control over every engage.',
    image: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Pyke_0.jpg',
    crest: './assets/crests/shadow-isles.png',
    crestAlt: 'shadow isles crest',
    href: '#all-champions',
  },
  {
    name: 'APHELIOS',
    title: 'Weapon Pair Automation',
    laneLabel: 'Menu',
    lane: 'Q / W / R',
    systemLabel: 'Focus',
    system: 'Pairs + reactive',
    blurb:
      'Weapon logic, pair controls, killsteal, reactive options, safety rules, flee behavior, and per-enemy controls make this one of the deepest scripts in the lineup.',
    image: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Aphelios_0.jpg',
    crest: './assets/icons/content-type-champion.png',
    crestAlt: 'champion icon',
    href: '#all-champions',
  },
  {
    name: 'ZED',
    title: 'Shadow State Combat',
    laneLabel: 'Menu',
    lane: 'Combo + flash',
    systemLabel: 'Focus',
    system: 'Reactive + drawings',
    blurb:
      'Prediction, combo, harass, killsteal, Flash Tech, reactive settings, clear, last-hit, and low-HP drawing tools give Zed players a wide control surface.',
    image: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Zed_0.jpg',
    crest: './assets/icons/content-type-trending.png',
    crestAlt: 'trending icon',
    href: '#all-champions',
  },
];

export const rosterCards = [
  {
    name: 'BLITZ',
    role: 'Hook Prediction',
    label: 'RIFT+',
    description: 'Prediction settings, Auto Q logic, interrupt lists, anti-gapclose options, and keybind tools are all there when you want a hook-first setup.',
    image: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Blitzcrank_0.jpg',
    position: 'center top',
  },
  {
    name: 'JINX',
    role: 'Get Excited Reset',
    label: 'HOT',
    description: 'Prediction settings, spell pages, automatic options, killsteal tools, draw settings, and permashow keep Jinx fast to shape around your style.',
    image: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Jinx_0.jpg',
    position: 'center top',
  },
  {
    name: 'CAITLYN',
    role: 'Trap Logic',
    label: 'RIFT+',
    description: 'A Caitlyn setup for players who want cleaner lane pressure, trap control, and faster access to their core options.',
    image: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Caitlyn_0.jpg',
    position: 'center top',
  },
  {
    name: 'SENNA',
    role: 'Soul Farming',
    label: 'UPD',
    description: 'Updated support for players who want scaling utility, long-range pressure, and a clean Senna setup.',
    image: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Senna_0.jpg',
    position: 'center top',
  },
  {
    name: 'SAMIRA',
    role: 'S-Rank Combo',
    label: 'HOT',
    description: 'HOT-tagged for players who want fast combo flow, all-in pressure, and a setup that feels aggressive from the start.',
    image: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Samira_0.jpg',
    position: 'center top',
  },
  {
    name: 'ZOE',
    role: 'Arcane Logic',
    label: 'NEW',
    description: 'NEW-tagged Zoe support for players who want a more specialist pick with fast access to key controls.',
    image: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Zoe_0.jpg',
    position: 'center top',
  },
];

export const allChampionCards = [
  {
    name: 'EZREAL',
    label: 'HOT',
    role: 'Mystic Shot Prediction',
    description: 'Built for players who want prediction-heavy control and fast access to their Ezreal setup.',
    image: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ezreal_0.jpg',
    position: 'center top',
  },
  {
    name: 'ZERI',
    label: 'UPD',
    role: 'The Spark of Zaun',
    description: 'Updated support for players who want a lighter, mobile marksman profile with core settings close at hand.',
    image: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Zeri_0.jpg',
    position: 'center top',
  },
  {
    name: 'JINX',
    label: 'HOT',
    role: 'Get Excited Reset',
    description: 'A high-tempo marksman entry with prediction, automatic options, draw settings, and killsteal pages.',
    image: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Jinx_0.jpg',
    position: 'center top',
  },
  {
    name: 'JAX',
    label: 'TEST',
    role: 'Leap Strike Test',
    description: 'Test-tagged Jax support for players tracking the current setup as it evolves.',
    image: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Jax_0.jpg',
    position: 'center top',
  },
  {
    name: 'YUNARA',
    label: 'NEW',
    role: 'New Champion',
    description: 'New champion support inside the lineup for players watching the latest additions.',
    image: './assets/latest/yunara.jpg',
    position: 'center center',
  },
  {
    name: 'ZAAHEN',
    label: 'NEW',
    role: 'The Unsundered',
    description: 'A newer lineup entry for players who want early access to fresh Rift+ support.',
    image: './assets/hero/zaahen.jpg',
    position: 'center top',
  },
  {
    name: "KOG'MAW",
    label: 'RIFT+',
    role: 'Orbwalker Limit',
    description: 'A dedicated Kog’Maw entry built for players who want fast access to core settings.',
    image: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/KogMaw_0.jpg',
    position: 'center top',
  },
  {
    name: 'TWITCH',
    label: 'RIFT+',
    role: 'Stealth Logic',
    description: 'A Twitch setup for players who like stealth pressure and champion-specific control.',
    image: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Twitch_0.jpg',
    position: 'center top',
  },
  {
    name: 'SAMIRA',
    label: 'HOT',
    role: 'S-Rank Combo',
    description: 'HOT-tagged for players who want fast all-in flow and a setup that stays aggressive.',
    image: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Samira_0.jpg',
    position: 'center top',
  },
  {
    name: 'APHELIOS',
    label: 'NEW',
    role: 'Weapon Pair Automation',
    description: 'One of the deepest entries in the lineup, built around weapon-pair control and reactive options.',
    image: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Aphelios_0.jpg',
    position: 'center top',
  },
  {
    name: 'CAITLYN',
    label: 'RIFT+',
    role: 'Trap Logic',
    description: 'A Caitlyn setup for players who want cleaner lane pressure, trap control, and fast menu access.',
    image: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Caitlyn_0.jpg',
    position: 'center top',
  },
  {
    name: "KAI'SA",
    label: 'RIFT+',
    role: 'Void Seeker',
    description: 'A focused Kai’Sa entry for players who want a quick, clean setup around core combat controls.',
    image: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Kaisa_0.jpg',
    position: 'center top',
  },
  {
    name: 'SHYVANA',
    label: 'NEW',
    role: 'Dragon Form Control',
    description: 'New-tagged support for players who want dragon-form pressure inside a dedicated Shyvana entry.',
    image: './assets/hero/shyvana.jpg',
    position: 'center top',
  },
  {
    name: 'QIYANA',
    label: 'NEW',
    role: 'Element Combo Control',
    description: 'New-tagged support for players who want tighter element-based setup and quick access to key controls.',
    image: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Qiyana_0.jpg',
    position: 'center top',
  },
  {
    name: 'ZED',
    label: 'NEW',
    role: 'Shadow State Combat',
    description: 'Built for assassin players who want shadow control, flash tools, and deeper setup pages.',
    image: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Zed_0.jpg',
    position: 'center top',
  },
  {
    name: 'SENNA',
    label: 'UPD',
    role: 'Soul Farming',
    description: 'Updated support for players who want long-range utility, scaling pressure, and a clean Senna setup.',
    image: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Senna_0.jpg',
    position: 'center top',
  },
  {
    name: 'TRISTANA',
    label: 'RIFT+',
    role: 'Explosive Charge',
    description: 'A Tristana entry made for players who want explosive all-in setup without menu clutter.',
    image: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Tristana_0.jpg',
    position: 'center top',
  },
  {
    name: 'MILIO',
    label: 'RIFT+',
    role: 'Campfire Support',
    description: 'A dedicated Milio entry for players who want support-focused control and clean access to key options.',
    image: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Milio_0.jpg',
    position: 'center top',
  },
  {
    name: 'BLITZ',
    label: 'RIFT+',
    role: 'Hook Prediction',
    description: 'A hook-first setup with prediction pages and quick access to utility tools.',
    image: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Blitzcrank_0.jpg',
    position: 'center top',
  },
  {
    name: 'PYKE',
    label: 'RIFT+',
    role: 'Execute Resets',
    description: 'An engage-heavy entry with execute focus, E tools, and the control to play aggressive.',
    image: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Pyke_0.jpg',
    position: 'center top',
  },
  {
    name: 'ORIANNA',
    label: 'RIFT+',
    role: 'Ball Management',
    description: 'A dedicated Orianna setup for players who want ball control and clean access to core pages.',
    image: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Orianna_0.jpg',
    position: 'center top',
  },
  {
    name: 'XERATH',
    label: 'RIFT+',
    role: 'Sniper Mode',
    description: 'Made for players who want long-range pressure and quick access to their artillery setup.',
    image: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Xerath_0.jpg',
    position: 'center top',
  },
  {
    name: 'SERAPHINE',
    label: 'RIFT+',
    role: 'Double Cast',
    description: 'A dedicated Seraphine entry for players who want supportive control with clean menu access.',
    image: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Seraphine_0.jpg',
    position: 'center top',
  },
  {
    name: 'CORKI',
    label: 'RIFT+',
    role: 'Package Timer',
    description: 'A focused Corki entry for players who want package timing support and fast core setup.',
    image: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Corki_0.jpg',
    position: 'center top',
  },
  {
    name: 'OLAF',
    label: 'RIFT+',
    role: 'Axe Spam',
    description: 'A direct Olaf entry for players who want aggressive settings without extra clutter.',
    image: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Olaf_0.jpg',
    position: 'center top',
  },
  {
    name: 'CASSIO',
    label: 'RIFT+',
    role: 'Twin Fang',
    description: 'A dedicated Cassiopeia entry for players who want quick access to core poison-fight control.',
    image: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Cassiopeia_0.jpg',
    position: 'center top',
  },
  {
    name: 'MEL',
    label: 'NEW',
    role: 'Arcane Logic',
    description: 'New-tagged support for players who want one of the newer arcane-flavored entries in the lineup.',
    image: './assets/latest/mel.jpg',
    position: 'center top',
  },
  {
    name: 'ZOE',
    label: 'NEW',
    role: 'Arcane Logic',
    description: 'New-tagged Zoe support for players who want a specialist setup and faster access to key controls.',
    image: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Zoe_0.jpg',
    position: 'center top',
  },
  {
    name: 'SYNDRA',
    label: 'NEW',
    role: 'Sphere Control',
    description: 'New-tagged support for players who want tighter sphere control inside a dedicated entry.',
    image: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Syndra_0.jpg',
    position: 'center top',
  },
  {
    name: 'XAYAH',
    label: 'NEW',
    role: 'Arcane Logic',
    description: 'New-tagged support for players who want feather-focused setup in the current Rift+ lineup.',
    image: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Xayah_0.jpg',
    position: 'center top',
  },
];

export const changelogEntries = [
  {
    version: 'Lineup',
    date: '30 entries',
    type: 'visible tags',
    title: 'The lineup stays broad and easy to read.',
    bullets: [
      'HOT tags currently appear on Ezreal, Jinx, and Samira.',
      'UPD tags appear on Zeri and Senna.',
      'NEW tags appear on entries such as Yunara, Aphelios, Shyvana, Qiyana, Zed, Mel, Zoe, Syndra, and Xayah.',
    ],
  },
  {
    version: 'Menus',
    date: 'player controls',
    type: 'common sections',
    title: 'The controls stay centered on real gameplay.',
    bullets: [
      'Combo, Harass, and Clear appear widely across the champion menus.',
      'Drawings and Killsteal settings are common menu sections.',
      'Selected scripts add reactive options, semi-manual keys, and per-enemy pages.',
    ],
  },
  {
    version: 'Support',
    date: 'Telegram + Discord',
    type: 'quick access',
    title: 'Community access stays close to the action.',
    bullets: [
      'Telegram is linked directly in the suite.',
      'Discord is linked directly in the suite.',
      'English and Chinese text paths are available across the UI.',
    ],
  },
];

export const supportLinks = [
  { text: 'Highlights', href: '#roster' },
  { text: 'Full lineup', href: '#all-champions' },
  { text: 'Discord', href: 'https://dsc.gg/danzaio' },
];
